services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - shared_data:/app/shared
  
  # Backend service
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CHARTS_DIR=/app/shared
    volumes:
      - ./backend:/app
      - shared_data:/app/shared

volumes:
  shared_data: